##Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [6]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [9]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.random.random((3,3))

array([[0.65087011, 0.64677106, 0.89684709],
       [0.00978883, 0.77165818, 0.26203219],
       [0.07939923, 0.76110782, 0.96780406]])

In [14]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attributes

In [16]:
a1=np.arange(10, dtype=np.int32)
a2=np.arange(12, dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

### ndim

In [17]:
a1.ndim

1

In [18]:
a2.ndim

2

In [19]:
a3.ndim

3

### size

In [20]:
a1.size

10

In [21]:
a2.size


12

### itemsize

In [22]:
a1.itemsize

4

In [23]:
a2.itemsize

8

### dtype

In [24]:
print(a1.dtype)
print(a.dtype)
print(a1.dtype)

int32
int64
int32


In [25]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [26]:
a3.dtype

dtype('int64')

## Array Operations

In [27]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [28]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [29]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [30]:
# vector operations
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [31]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[33., 73., 83.],
       [31., 26., 38.],
       [93., 31., 38.]])

In [32]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=0)

array([93., 73., 83.])

In [33]:
# mean/median/std/var
np.var(a1,axis=1)

array([466.66666667,  24.22222222, 768.66666667])

In [34]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.99991186, -0.67677196,  0.96836446],
       [-0.40403765,  0.76255845,  0.29636858],
       [-0.94828214, -0.40403765,  0.29636858]])

In [35]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [36]:
# log and exponents
np.exp(a1)

array([[2.14643580e+14, 5.05239363e+31, 1.11286375e+36],
       [2.90488497e+13, 1.95729609e+11, 3.18559318e+16],
       [2.45124554e+40, 2.90488497e+13, 3.18559318e+16]])

In [37]:
# round/floor/ceil

print(np.round(np.random.random((2,3))*100))
print()
print(np.floor(np.random.random((2,3))*100))
print()
print(np.ceil(np.random.random((2,3))*100))

[[40. 93. 89.]
 [15. 15. 59.]]

[[99. 10. 89.]
 [74. 15. 66.]]

[[47. 83.  5.]
 [75. 87. 46.]]


## Indexing and Slicing

In [46]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [47]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
a2[1,0]

4

In [50]:
a3[1,0,1]

5

In [51]:
a3[1,1,0]

6

In [52]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a1[2:5:2]

array([2, 4])

In [54]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [55]:
a2[0::2,0::3]

array([[ 0,  3],
       [ 8, 11]])

In [56]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [57]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [60]:
 a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [61]:
a2[1,::3]

array([4, 7])

In [62]:
a2[0,:]

array([0, 1, 2, 3])

In [63]:
a2[:,2]

array([ 2,  6, 10])

In [64]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [65]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [67]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [69]:
a3[0,1,:]

array([3, 4, 5])

In [70]:
a3[1,:,1]

array([10, 13, 16])

In [71]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [72]:
a3[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

In [75]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [79]:
np.transpose(a2)
a2.T       # shorter

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [80]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [84]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Stacking

In [86]:
# Horizotal Stacking
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

In [88]:
# Vertical Stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [91]:
# Horizotal Splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [94]:
# Verical Splitting
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]