### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [2]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[40, 45, 47, 32],
       [39, 57, 92,  1],
       [41, 52, 69, 59],
       [66, 60,  3, 59],
       [40, 30, 98, 92],
       [72, 22,  7, 79]])

In [3]:
np.sort(a)

array([ 9, 13, 31, 34, 41, 51, 51, 56, 71, 75, 77, 80, 86, 91, 97])

In [4]:
np.sort(a)[::-1]

array([97, 91, 86, 80, 77, 75, 71, 56, 51, 51, 41, 34, 31, 13,  9])

In [5]:
np.sort(b)

array([[32, 40, 45, 47],
       [ 1, 39, 57, 92],
       [41, 52, 59, 69],
       [ 3, 59, 60, 66],
       [30, 40, 92, 98],
       [ 7, 22, 72, 79]])

In [6]:
np.sort(b,axis=0)

array([[39, 22,  3,  1],
       [40, 30,  7, 32],
       [40, 45, 47, 59],
       [41, 52, 69, 59],
       [66, 57, 92, 79],
       [72, 60, 98, 92]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [7]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [8]:
np.append(a,200)

array([  9,  86,  31,  91,  71,  56,  80,  97,  13,  51,  41,  51,  75,
        34,  77, 200])

In [9]:
b

array([[40, 45, 47, 32],
       [39, 57, 92,  1],
       [41, 52, 69, 59],
       [66, 60,  3, 59],
       [40, 30, 98, 92],
       [72, 22,  7, 79]])

In [10]:
b.shape[0]

6

In [11]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[4.00000000e+01, 4.50000000e+01, 4.70000000e+01, 3.20000000e+01,
        6.14150852e-02],
       [3.90000000e+01, 5.70000000e+01, 9.20000000e+01, 1.00000000e+00,
        3.96248496e-01],
       [4.10000000e+01, 5.20000000e+01, 6.90000000e+01, 5.90000000e+01,
        3.40952718e-01],
       [6.60000000e+01, 6.00000000e+01, 3.00000000e+00, 5.90000000e+01,
        3.23766385e-01],
       [4.00000000e+01, 3.00000000e+01, 9.80000000e+01, 9.20000000e+01,
        8.83895094e-02],
       [7.20000000e+01, 2.20000000e+01, 7.00000000e+00, 7.90000000e+01,
        5.99382340e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [12]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [13]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [15]:
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [16]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [17]:
a.shape

(15,)

In [18]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [19]:
np.expand_dims(a,axis=1)

array([[ 9],
       [86],
       [31],
       [91],
       [71],
       [56],
       [80],
       [97],
       [13],
       [51],
       [41],
       [51],
       [75],
       [34],
       [77]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [20]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [21]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  3,  4,  5,  6,  7,  9, 11, 12, 14]),)

In [22]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 9,  0, 31,  0,  0,  0,  0,  0, 13,  0, 41,  0,  0, 34,  0])

In [23]:
np.where(a%2 == 0,0,a)

array([ 9,  0, 31, 91, 71,  0,  0, 97, 13, 51, 41, 51, 75,  0, 77])

np.argmax
The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [24]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [25]:
np.argmax(a)

7

In [26]:
b

array([[40, 45, 47, 32],
       [39, 57, 92,  1],
       [41, 52, 69, 59],
       [66, 60,  3, 59],
       [40, 30, 98, 92],
       [72, 22,  7, 79]])

In [27]:
np.argmax(b,axis=0)

array([5, 3, 4, 4])

In [28]:
np.argmax(b,axis=1)

array([2, 2, 2, 0, 2, 3])

In [29]:
np.argmin(a)

0

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [30]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [31]:
np.cumsum(a)

array([  9,  95, 126, 217, 288, 344, 424, 521, 534, 585, 626, 677, 752,
       786, 863])

In [32]:
b

array([[40, 45, 47, 32],
       [39, 57, 92,  1],
       [41, 52, 69, 59],
       [66, 60,  3, 59],
       [40, 30, 98, 92],
       [72, 22,  7, 79]])

In [33]:
np.cumsum(b,axis=1)

array([[ 40,  85, 132, 164],
       [ 39,  96, 188, 189],
       [ 41,  93, 162, 221],
       [ 66, 126, 129, 188],
       [ 40,  70, 168, 260],
       [ 72,  94, 101, 180]])

In [34]:
np.cumsum(b)

array([  40,   85,  132,  164,  203,  260,  352,  353,  394,  446,  515,
        574,  640,  700,  703,  762,  802,  832,  930, 1022, 1094, 1116,
       1123, 1202])

In [35]:
# np.cumprod
np.cumprod(a)

array([                   9,                  774,                23994,
                    2183454,            155025234,           8681413104,
               694513048320,       67367765687040,      875780953931520,
          44664828650507520,  1831257974670808320,  1160436339663466240,
       -5200994893787790080,  7633614348310653440, -2507505538785336832])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [36]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [37]:
np.percentile(a,50)

56.0

In [38]:
np.median(a)

56.0

In [39]:
np.percentile(a,100)

97.0

In [40]:
np.percentile(a,0)

9.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [41]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [42]:
np.histogram(a,bins=[0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [43]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [44]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [45]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([80])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [46]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [47]:
np.flip(a)

array([77, 34, 75, 51, 41, 51, 13, 97, 80, 56, 71, 91, 31, 86,  9])

In [48]:
b

array([[40, 45, 47, 32],
       [39, 57, 92,  1],
       [41, 52, 69, 59],
       [66, 60,  3, 59],
       [40, 30, 98, 92],
       [72, 22,  7, 79]])

In [49]:
np.flip(b,axis=1)

array([[32, 47, 45, 40],
       [ 1, 92, 57, 39],
       [59, 69, 52, 41],
       [59,  3, 60, 66],
       [92, 98, 30, 40],
       [79,  7, 22, 72]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [50]:
a

array([ 9, 86, 31, 91, 71, 56, 80, 97, 13, 51, 41, 51, 75, 34, 77])

In [51]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [52]:
a

array([110, 530,  31,  91,  71,  56,  80,  97,  13,  51,  41,  51,  75,
        34,  77])

In [53]:
np.delete(a,[0,2,4])

array([530,  91,  56,  80,  97,  13,  51,  41,  51,  75,  34,  77])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [54]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [55]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(n,m)

array([6, 7])

In [57]:
np.setdiff1d(m,n)

array([1, 2])

In [58]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [59]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [60]:
a

array([110, 530,  31,  91,  71,  56,  80,  97,  13,  51,  41,  51,  75,
        34,  77])

In [61]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 31, 75, 71, 56, 75, 75, 25, 51, 41, 51, 75, 34, 75])